# Generated by Django 3.1.2 on 2020-11-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emailotp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane1', models.IntegerField()),
                ('plane2', models.IntegerField()),
                ('plane3', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
