# Generated by Django 3.0.8 on 2020-10-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic',
            old_name='campany_name',
            new_name='name',
        ),
    ]
