# Generated by Django 3.0.8 on 2020-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0002_auto_20201027_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
