# Generated by Django 3.0.3 on 2020-10-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0004_auto_20201027_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
