# Generated by Django 3.0.3 on 2020-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0005_auto_20201027_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='company_name',
        ),
        migrations.AddField(
            model_name='basic',
            name='company_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Headquatars',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Industry_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='founded',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='incorporation_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='logo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='register_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='specialities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
