# Generated by Django 3.0.8 on 2020-10-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0006_auto_20201027_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='crack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='image')),
            ],
        ),
    ]
