<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-03 05:30
=======
# Generated by Django 3.1.2 on 2020-11-03 05:17
>>>>>>> origin/main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0010_auto_20201028_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crack',
        ),
    ]
