# Generated by Django 3.1.2 on 2020-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0011_delete_crack'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='Company_Registered_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='Roc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='cin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='director_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
