# Generated by Django 3.1.2 on 2020-11-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyData', '0014_basic_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='director_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
